[package]
name = "lab1"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
native-tls = "0.2.12"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
select = "0.6.0"
url = "2.5.2"
