services:
  lab2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Maps container port 8080 to host
    volumes:
      - .:/lab2
    environment:
      - DATABASE_URL=sqlite:///app/db.sqlite
      - JWT_SECRET="anysecrethere"
      - RUST_LOG=info
    depends_on:
      - lab2-db
    command: ["cargo", "run", "--bin", "seed"]

  lab2-db:
    image: nouchka/sqlite3
    volumes:
      - ./db:/lab2/db
    environment:
      - SQLITE_DB_NAME=db.sqlite
